
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: springcloud-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    pool:
    max-active: 20
    max-wait: -1
    max-idle: 8
    min-idle: 0

mybatis:
  mapper-locations: classpath:/mybatis/*.xml



